In [5]:
import cv2
import numpy as np
from matplotlib import pyplot
import pandas

In [7]:
# Load the image that contains an object 
df_read = pandas.read_pickle('test.pickle')

In [9]:
df_read.describe()

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
count,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,...,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000
mean,137.851048,137.966910,138.131854,137.575740,137.372611,138.095557,138.149125,137.849841,138.025971,138.190222,...,138.316898,137.855169,138.197263,138.115185,138.494748,137.969438,138.113199,138.152318,137.884250,138.056684
std,5.716253,5.731547,5.737117,5.880285,5.672013,5.545342,5.815480,5.579570,5.811493,6.087916,...,5.722205,5.913465,5.787558,5.660307,5.540237,5.685743,5.954375,5.665549,5.763778,5.787477
min,128.001534,128.008529,128.006525,128.031144,128.030442,128.073037,128.078680,128.031171,128.053189,128.008625,...,128.010210,128.025749,128.044310,128.030516,128.163617,128.081023,128.013819,128.006848,128.015442,128.010605
25%,133.085307,133.051131,133.204913,132.518427,132.592688,133.341719,133.282545,133.172998,133.045582,132.674551,...,133.533391,132.651527,133.480729,133.342114,133.605669,132.839789,132.881021,133.433970,132.809220,133.171360
50%,137.823116,138.201296,138.264352,137.549512,136.864734,138.155218,138.096961,137.637413,138.236261,138.085778,...,138.497223,137.463448,138.308688,137.995970,138.827276,138.278103,138.175971,138.209106,137.771122,137.842358
75%,142.721836,142.872078,142.801282,142.672376,142.091624,142.747951,142.969337,142.667127,142.974328,143.743328,...,143.108540,143.168225,143.571214,143.157402,143.331848,142.477078,143.778886,142.691477,142.950213,143.387617
max,147.987938,147.971232,147.928219,147.980304,147.936725,147.974652,147.968252,147.965462,147.990745,147.999610,...,147.984533,147.998252,147.995900,147.992375,147.976857,147.909230,147.983700,147.988222,147.968938,147.990120